language: ruby
rvm:
  - 2.0.0-p648
  - 2.1.10
  - 2.2.8
  - 2.3.6
  - 2.4.2
  - 2.5.0
  - ruby-head
  - jruby-9.1.13.0    
  - jruby-head 
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

gemfile:
  - Gemfile
  
# whitelist
branches:  
  only:
    - master