language: ruby
matrix:
  include:
    - rvm: 2.0.0
    - rvm: 2.1.10
    - rvm: 2.2.6
    - rvm: 2.3.3
    - rvm: ruby-head
    - rvm: rbx-3
    - rvm: jruby-9.0.1.0    
    - rvm: jruby-head     

  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-3
    - rvm: jruby-head     

gemfile:
  - Gemfile
  
# whitelist
branches:  
  only:
    - master