language: ruby
rvm:
  - 2.0.0
  - 2.1.9
  - 2.2.6
  - 2.3.3
  - ruby-head
  - rbx-3
  - jruby-9.0.1.0    
  - jruby-head 
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-3
    - rvm: jruby-head

gemfile:
  - Gemfile
  
# whitelist
branches:  
  only:
    - master